# Generated by Django 2.2.6 on 2019-10-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='aaa', max_length=200),
            preserve_default=False,
        ),
    ]
