# Generated by Django 2.2.6 on 2019-10-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191021_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapusersurvey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='polls.Person'),
        ),
    ]
