# Generated by Django 2.2.6 on 2019-10-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191021_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapusersurvey',
            old_name='user',
            new_name='person',
        ),
    ]
