# Generated by Django 2.2.6 on 2019-10-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191021_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapusersurvey',
            name='random_letters',
            field=models.CharField(default='aaaaa', max_length=5),
            preserve_default=False,
        ),
    ]
