# Generated by Django 2.2.6 on 2019-10-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20191024_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='data_number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='data_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
