# Generated by Django 2.2.6 on 2019-10-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20191024_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='data_number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='data_text',
        ),
    ]
