# Generated by Django 2.2.6 on 2019-10-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20191024_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsurveyquestion',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
