# Generated by Django 2.2.6 on 2019-11-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20191024_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='num_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
