# Generated by Django 2.2.6 on 2019-11-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_choice_num_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapsurveyquestion',
            unique_together={('survey', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='mapusersurvey',
            unique_together={('person', 'survey')},
        ),
    ]
