# Generated by Django 2.2.6 on 2019-11-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20191112_1046'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapsurveyquestion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mapusersurvey',
            unique_together=set(),
        ),
    ]
