# Generated by Django 2.2.6 on 2019-11-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20191112_1512'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapsurveyquestion',
            unique_together=set(),
        ),
    ]
