# Generated by Django 2.2.6 on 2019-12-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20191113_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsurveyquestion',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
    ]
