# Generated by Django 2.2.6 on 2020-01-04 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_mapsurveyquestion_is_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='create_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='data_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('NUMBER_RANGE', 'Numeric Range'), ('MSMC', 'Multi Select'), ('SSMC', 'Single Select')], default='SSMC', max_length=50),
        ),
    ]
